<?php

namespace FernleafSystems\ApiWrappers\StatusCake\Tests;

use Elliotchance\Iterator\AbstractPagedIterator;

class TestIterator extends AbstractPagedIterator {

	public const MIN_PAGE_SIZE = 1;
	public const MAX_PAGE_SIZE = 100;

	private int $pageSize = 25;

	public ?RetrieveAll $retriever;

	public function __construct( ?RetrieveAll $retriever ) {
		$this->retriever = $retriever;
	}

	/**
	 * @return TestVO
	 */
	public function current() {
		return parent::current(); // TODO: Change the autogenerated stub
	}

	/**
	 * @inheritDoc
	 */
	public function getPageSize() {
		return min( self::MAX_PAGE_SIZE, max( self::MIN_PAGE_SIZE, $this->pageSize ) );
	}

	/**
	 * @inheritDoc
	 */
	public function getTotalSize() {
		// TODO: Implement getTotalSize() method.
	}

	/**
	 * @inheritDoc
	 */
	public function getPage( $pageNumber ) {
		return $this->retriever->setPage( $pageNumber + 1 )
							   ->setLimit( $this->getPageSize() )
							   ->getAllAsTestVO();
	}

	public function setPageSize( int $pageSize ) :self {
		$this->pageSize = $pageSize;
		return $this;
	}
}